### ISSUE TITLE
Tracking of SoD Tuning Auras

### ISSUE THREAD

**Issue by sanguinerarogue** [wowsims/classic#28]
https://www.wowhead.com/classic/search?q=tuning#abilities

- [ ] https://www.wowhead.com/classic/spell=462814/s03-tuning-and-overrides-passive-paladin
- [ ] https://www.wowhead.com/classic/spell=446658/s03-tuning-and-overrides-passive-warrior
- [ ] https://www.wowhead.com/classic/spell=466503/s03-tuning-and-overrides-passive-paladin
- [ ] https://www.wowhead.com/classic/spell=462659/s03-tuning-and-overrides-passive-hunter
- [ ] https://www.wowhead.com/classic/spell=453124/s03-tuning-and-overrides-passive-druid
- [ ] https://www.wowhead.com/classic/spell=442543/s03-tuning-and-overrides-passive-mage
- [ ] https://www.wowhead.com/classic/spell=440247/s03-tuning-and-overrides-passive-priest
- [ ] https://www.wowhead.com/classic/spell=436895/s03-tuning-and-overrides-passive-druid
- [ ] https://www.wowhead.com/classic/spell=446374/s03-tuning-and-overrides-passive-hunter
- [ ] https://www.wowhead.com/classic/spell=435884/s03-tuning-and-overrides-passive-shaman

Tracking to ensure tuning auras are undone.
